import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { spawn } from 'node:child_process';
import { mkdir } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
const { chromium } = createRequire(import.meta.url)('playwright');
const server = spawn(process.execPath, ['serve.mjs'], { stdio: ['ignore', 'pipe', 'inherit'], env: { ...process.env, PORT: '4174' } });
await new Promise((resolve, reject) => { server.stdout.once('data', resolve); server.once('error', reject); server.once('exit', code => reject(new Error(`Server exited: ${code}`))); });
let browser;
try {
  browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE } : {}) });
  await mkdir('test-artifacts', { recursive: true });
  for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
    const context = await browser.newContext({ viewport, reducedMotion: 'reduce' });
    // Keep this repeatable offline: local catalogue remains usable with every online request blocked.
    await context.route('https://**/*', route => route.abort());
    const page = await context.newPage();
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto('http://127.0.0.1:4174');
    assert.equal(await page.evaluate(() => musicEnabled), true);
    assert.equal(await page.locator('#music').evaluate(button => !!button.closest('header .global-controls')), true);
    await page.locator('.intro h1').click();
    await page.waitForFunction(() => !backgroundMusic.paused && backgroundMusic.currentTime > 0);
    assert.equal(await page.evaluate(() => backgroundMusic.loop), true);
    await page.locator('#sound').click();
    assert.equal(await page.evaluate(() => backgroundMusic.paused), false);
    await page.locator('#music').click();
    assert.equal(await page.evaluate(() => backgroundMusic.paused), true);
    await page.mouse.wheel(0, 50);
    assert.equal(await page.evaluate(() => backgroundMusic.paused), true, 'scroll does not undo an explicit OFF choice');
    await page.reload();
    assert.equal(await page.locator('#music').getAttribute('aria-pressed'), 'false');
    assert.equal(await page.evaluate(() => backgroundMusic.paused), true, 'explicit OFF survives reload');
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: `test-artifacts/start-${viewport.width}.png` });
    await page.locator('#tab-collection').click();
    await page.locator('#edit-toggle').click();
    const draft = '  Draft with  spaces\n\nSecond film\n';
    await page.locator('#movies').fill(draft);
    await page.locator('#movies').evaluate(input => input.setSelectionRange(5, 5));
    await page.locator('#movies').press('x');
    const edited = await page.locator('#movies').inputValue();
    assert.equal(edited, draft.slice(0, 5) + 'x' + draft.slice(5));
    assert.equal(await page.locator('#movies').evaluate(input => input.selectionStart), 6);
    assert.equal(await page.locator('#count').textContent(), '19');
    await page.locator('#cancel-edit').click();
    assert.equal(await page.locator('#count').textContent(), '19');
    await page.locator('#edit-toggle').click();
    await page.locator('#movies').fill(Array.from({ length: 61 }, (_, i) => `Movie ${i}`).join('\n'));
    await page.locator('#finish-edit').click();
    assert.equal(await page.locator('#movie-editor').isVisible(), true);
    assert.match(await page.locator('#editor-error').textContent(), /60/);
    await page.locator('#movies').fill('  One film\nOne film\nSecond film\n');
    await page.locator('#finish-edit').click();
    assert.equal(await page.locator('#count').textContent(), '2');
    const before = await page.evaluate(() => JSON.parse(localStorage.getItem('cinema-roulette-v5')).themes.halloween.playlist[0]);
    await page.locator('.movie-row-actions button').first().click();
    await page.locator('#title-edit-input').fill('Renamed film');
    await page.locator('#title-edit-save').click();
    await page.waitForFunction(() => document.activeElement === document.querySelector('.movie-row-actions button'));
    const after = await page.evaluate(() => JSON.parse(localStorage.getItem('cinema-roulette-v5')).themes.halloween.playlist[0]);
    assert.equal(after.id, before.id); assert.equal(after.title, 'Renamed film');
    await page.locator('.movie-row-actions button').nth(1).click();
    assert.equal(await page.locator('#count').textContent(), '1');
    await page.locator('#undo-remove').click();
    assert.equal(await page.locator('#count').textContent(), '2');
    await page.screenshot({ path: `test-artifacts/collection-viewport-${viewport.width}.png` });
    // The canvas has a semantic keyboard equivalent with every eligible title.
    const summary = page.locator('#eligible-list-label');
    await summary.focus(); await page.keyboard.press('Enter'); await page.keyboard.press('Tab');
    assert.equal(await page.evaluate(() => document.activeElement === document.querySelector('#eligible-list button')), true);
    await page.keyboard.press('Enter');
    assert.equal(await page.locator('#movie-dialog').evaluate(dialog => dialog.open), true);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#movie-dialog').evaluate(dialog => dialog.open), false);
    assert.equal(await page.evaluate(() => document.activeElement === document.querySelector('#eligible-list button')), true);
    await page.locator('#discover-summary').click();
    const poster = page.locator('#catalog-results button.movie-poster').first();
    await poster.focus(); await page.keyboard.press('Enter');
    assert.equal(await page.locator('#movie-dialog').evaluate(dialog => dialog.open), true);
    await page.locator('#movie-dialog-close').click();
    assert.equal(await poster.evaluate(button => document.activeElement === button), true);
    await page.screenshot({ path: `test-artifacts/collection-${viewport.width}.png`, fullPage: true });
    const overflow = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth, elements: [...document.querySelectorAll('body *')].filter(el => el.getBoundingClientRect().right > innerWidth + 1 && el.getBoundingClientRect().width).map(el => `${el.tagName}#${el.id}.${el.className}`).slice(0, 20) }));
    assert.equal(overflow.scroll <= overflow.width, true, `no horizontal overflow: ${JSON.stringify(overflow)}`);
    assert.deepEqual(errors, []);
    await page.locator('#edit-toggle').click();
    await page.locator('#movies').fill(Array.from({ length: 60 }, (_, i) => `Long list film ${i}`).join('\n'));
    await page.locator('#finish-edit').click();
    assert.equal(await page.locator('#draw-mode').inputValue(), 'wheel');
    assert.equal(await page.locator('#poster-suggestion').isVisible(), true);
    assert.equal(await page.locator('#eligible-list button').count(), 60);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.locator('#draw-mode').selectOption('posters');
    assert.equal(await page.locator('#poster-suggestion').isVisible(), false);
    await page.locator('#language').selectOption('en');
    await page.locator('#theme').selectOption('christmas');
    assert.equal(await page.locator('#count').textContent(), '13');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: `test-artifacts/christmas-${viewport.width}.png` });
    await page.locator('#theme').selectOption('halloween');
    assert.equal(await page.locator('#count').textContent(), '60');
    assert.equal(await page.locator('#draw-mode').inputValue(), 'posters');
    await page.locator('#draw-mode').selectOption('doors');
    await page.locator('#spin').click();
    assert.equal(await page.locator('.mystery-door').count(), 3);
    assert.equal(await page.locator('.mystery-door').evaluateAll(doors => new Set(doors.map(door => getComputedStyle(door).backgroundImage)).size), 3);
    await page.locator('#doors-stage').scrollIntoViewIfNeeded();
    await page.screenshot({ path: `test-artifacts/doors-${viewport.width}.png` });
    await page.locator('.mystery-door').first().focus(); await page.keyboard.press('Enter');
    await page.waitForFunction(() => !spinning);
    assert.equal(await page.locator('.mystery-door.is-open').count(), 1);
    for (const file of ['audio/zombie.mp3', 'audio/witch-laugh.mp3', 'audio/witch-laugh-evil.mp3', 'door-ghost.wav']) {
      assert.equal(await page.evaluate(async src => {
        const audio = new Audio(src);
        return await new Promise(resolve => { audio.addEventListener('loadedmetadata', () => resolve(audio.duration > 0), { once: true }); audio.addEventListener('error', () => resolve(false), { once: true }); });
      }, file), true, `browser decodes ${file}`);
    }
    await context.close();
  }
  // Actual browser quota failure: preserve the committed memory state and offer its backup.
  const context = await browser.newContext();
  await context.route('https://**/*', route => route.abort());
  await context.addInitScript(() => { Storage.prototype.setItem = () => { throw new DOMException('Quota', 'QuotaExceededError'); }; });
  const page = await context.newPage(); await page.goto('http://127.0.0.1:4174');
  assert.equal(await page.locator('#storage-warning').isVisible(), true);
  await page.locator('#tab-collection').click(); await page.locator('#edit-toggle').click();
  await page.locator('#movies').fill('Memory movie'); await page.locator('#finish-edit').click();
  assert.equal(await page.locator('#count').textContent(), '1');
  const downloadPromise = page.waitForEvent('download'); await page.locator('#storage-backup').click();
  assert.equal((await downloadPromise).suggestedFilename(), 'halloween-roulette-backup.json');
  await context.close();
  const fileContext = await browser.newContext();
  await fileContext.route('https://**/*', route => route.abort());
  const filePage = await fileContext.newPage();
  const fileErrors = []; filePage.on('pageerror', error => fileErrors.push(error.message));
  await filePage.goto(pathToFileURL(resolve('index.html')).href);
  assert.equal(await filePage.locator('#count').textContent(), '19', 'classic scripts also run directly from disk');
  assert.deepEqual(fileErrors, []);
  await fileContext.close();
  const autoplayBrowser = await chromium.launch({ headless: true, args: ['--autoplay-policy=no-user-gesture-required'], ...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE } : {}) });
  try {
    const automaticPage = await autoplayBrowser.newPage();
    await automaticPage.route('https://**/*', route => route.abort());
    await automaticPage.goto('http://127.0.0.1:4174');
    await automaticPage.waitForFunction(() => !backgroundMusic.paused && backgroundMusic.currentTime > 0);
    assert.equal(await automaticPage.locator('#music').getAttribute('aria-pressed'), 'true', 'music plays on entry when browser policy permits');
  } finally { await autoplayBrowser.close(); }
  console.log('Passed Chromium: desktop/mobile editing, validation, IDs, undo, keyboard details, modal focus, semantic posters, layout, offline catalogue and storage failure.');
} finally { await browser?.close(); server.kill(); }
