import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import { webcrypto } from 'node:crypto';
import tmdbProxy, { CinemaRateLimiter } from './tmdb-proxy/worker.mjs';

const i18nKeys = ['workspaceEyebrow', 'workspaceTitle', 'tabSession', 'tabCollection', 'tabHistory', 'filmsNoun', 'findMovies', 'eyebrow', 'headline1', 'headline2', 'intro', 'wheelCaption', 'spin', 'collectionEyebrow', 'collectionTitle', 'collectionSummary', 'editMovies', 'editorHelp', 'moviesLabel', 'reset', 'finishEdit', 'filterTitle', 'surpriseTitle', 'metadataTitle', 'sharingTitle', 'portabilityTitle', 'historyEyebrow', 'clearHistory', 'historyNote', 'footerLeft', 'footerRight'];

async function createApp(seed = {}, options = {}) {
  const nodes = new Map();
  const downloads = [];
  const downloadNames = [];
  const clipboardWrites = [];
  function makeElement(selector) {
    const classes = new Set();
    const value = selector.match(/#(?:filter|metadata)-mood-(light|scary|nostalgic)$/)?.[1] ?? (selector === '#marathon-count' ? '3' : selector === '#draw-mode' ? 'wheel' : selector === '#draw-pace' ? 'fast' : '');
    const options = ['#theme', '#portability-theme'].includes(selector) ? [{ textContent: '', value: 'halloween' }, { textContent: '', value: 'christmas' }] : selector === '#draw-mode' ? ['wheel', 'doors', 'shuffle', 'posters'].map(value => ({ value, textContent: '' })) : selector === '#draw-pace' ? ['fast', 'suspense'].map(value => ({ value, textContent: '' })) : selector === '#playlist-import-mode' ? [{ textContent: '', value: 'merge' }, { textContent: '', value: 'replace' }] : selector === '#filter-duration' ? ['any', '90', '120', '150', '180'].map(value => ({ value, textContent: '' })) : [];
    const element = { selector, value, textContent: '', innerHTML: '', disabled: false, checked: false, hidden: false, children: [], attributes: {}, listeners: {}, style: {}, dataset: {}, options, files: [], classList: { add(...names) { names.forEach(name => classes.add(name)); }, remove(...names) { names.forEach(name => classes.delete(name)); }, toggle(name, force) { if (force ?? !classes.has(name)) classes.add(name); else classes.delete(name); }, contains: name => classes.has(name) }, addEventListener(type, fn) { this.listeners[type] = fn; }, dispatch(type) { return this.listeners[type]?.({ target: this, preventDefault() {} }); }, setAttribute(name, value) { this.attributes[name] = value; }, getAttribute(name) { return this.attributes[name] ?? null; }, removeAttribute(name) { delete this.attributes[name]; }, replaceChildren(...items) { this.children = items; if (this.selector.startsWith('select') || ['#surprise-mood', '#surprise-duration', '#metadata-movie'].includes(this.selector)) this.options = []; }, append(...items) { this.children.push(...items); if (this.selector.startsWith('select') || ['#surprise-mood', '#surprise-duration', '#metadata-movie'].includes(this.selector)) this.options.push(...items); }, querySelector(query) { const value = query.match(/\[value="([^"]+)"\]/)?.[1]; return this.options.find(option => option.value === value) ?? null; }, focus() { this.focused = true; }, click() { this.clicked = true; if (this.download) downloadNames.push(this.download); }, remove() { this.removed = true; } };
    element.firstElementChild = { style: {} };
    return element;
  }
  function node(selector) {
    if (!nodes.has(selector)) nodes.set(selector, makeElement(selector));
    return nodes.get(selector);
  }
  const canvasContext = { createRadialGradient() { return { addColorStop() {} }; }, clearRect() {}, save() {}, restore() {}, translate() {}, rotate() {}, beginPath() {}, moveTo() {}, arc() {}, closePath() {}, fill() {}, stroke() {}, fillText() {}, measureText: text => ({ width: text.length * 14 }) };
  node('#wheel').getContext = () => canvasContext;
  const storage = new Map(Object.entries(seed).map(([key, value]) => [key, JSON.stringify(value)]));
  const requests = [];
  const fetchImplementation = options.fetch ?? (async () => { throw new TypeError('offline'); });
  const fetchMock = async (url, requestOptions) => { requests.push({ url: String(url), requestOptions }); return fetchImplementation(url, requestOptions); };
  const windowObject = options.window ?? {};
  const audios = [];
  const animationFrames = [];
  let now = 0;
  let reduceMotion = false;
  let confirmDecision = false;
  let confirmMessage = '';
  class InstrumentedURL extends URL {
    static createObjectURL(blob) { downloads.push(blob); return `blob:test-${downloads.length}`; }
    static revokeObjectURL() {}
  }
  const urlImplementation = options.URL ?? InstrumentedURL;
  const sandbox = vm.createContext({ document: { querySelector: node, querySelectorAll: selector => selector === '[data-i18n]' ? i18nKeys.map(key => { const element = node(`i18n:${key}`); element.setAttribute('data-i18n', key); return element; }) : selector === '[data-collection]' ? ['all', 'halloween-family', 'horror', 'christmas-classics', 'christmas-family'].map(key => { const element = node(`collection:${key}`); element.setAttribute('data-collection', key); return element; }) : selector === '.mystery-door' ? node('#doors').children : [], documentElement: {}, body: node('body'), createElement: tag => makeElement(tag), fonts: null }, localStorage: { getItem: key => storage.get(key) ?? null, setItem: (key, value) => storage.set(key, value) }, Audio: class { constructor(src) { this.src = src; this.paused = true; this.playCount = 0; audios.push(this); } play() { this.paused = false; this.playCount++; return Promise.resolve(); } pause() { this.paused = true; } }, crypto: webcrypto, matchMedia: () => ({ matches: reduceMotion }), performance: { now: () => now }, requestAnimationFrame: fn => animationFrames.push(fn), confirm: message => { confirmMessage = message; return confirmDecision; }, URL: urlImplementation, AbortController, TextEncoder, TextDecoder, Uint8Array, btoa: value => Buffer.from(value, 'binary').toString('base64'), atob: value => Buffer.from(value, 'base64').toString('binary'), Blob, setTimeout, navigator: options.navigator ?? { clipboard: { writeText: async text => clipboardWrites.push(text) } }, location: options.location ?? { href: 'https://joaopef.github.io/halloween-roulette/' }, window: windowObject, fetch: fetchMock });
  vm.runInContext(await readFile('movies.js', 'utf8'), sandbox);
  vm.runInContext(await readFile('catalog.js', 'utf8'), sandbox);
  vm.runInContext(await readFile('app.js', 'utf8'), sandbox);
  return { node, storage, audios, animationFrames, sandbox, requests, downloads, downloadNames, clipboardWrites, setNow: value => { now = value; }, setReduceMotion: value => { reduceMotion = value; }, setConfirm: value => { confirmDecision = value; }, confirmMessage: () => confirmMessage };
}

const app = await createApp();
const { node, storage, audios, animationFrames, sandbox } = app;
const evaluate = expression => vm.runInContext(expression, sandbox);
assert.equal(node('#count').textContent, 19);
assert.equal(node('#eligibility-summary').hidden, true, 'do not repeat the total when every movie is eligible');
assert.equal(node('#movie-editor').hidden, true);
assert.equal(node('#edit-toggle').getAttribute('aria-expanded'), 'false');
assert.equal(node('#sound').getAttribute('aria-pressed'), 'true');
assert.equal(node('#sound').getAttribute('aria-label'), 'Desativar som');
assert.equal(node('#theme').value, 'halloween');
assert.equal(node('#catalog-results').children.length, 8, 'Halloween suggestions omit the 19 movies already on the wheel');
assert.equal(evaluate('CURATED_CATALOG.halloween.every(movie => safePosterUrl(movie.posterUrl))'), true, 'every curated Halloween film has a verified poster');
assert.equal(evaluate('playlistRecords().every(movie => safePosterUrl(movie.posterUrl))'), true, 'all 19 starter titles receive posters without changing their identity');
assert.match(node('#catalog-status').textContent, /TMDB não está ativa/);
assert.equal(node('#tmdb-attribution').hidden, true, 'inactive TMDB does not claim an active integration');
assert.equal(node('#history-stats').textContent, '17 filmes diferentes · 24 sorteios');
assert.equal(node('#history').children.length, 5);
assert.equal(evaluate("playlistRecords().find(movie => movie.title === 'Beetlejuice (1988)').runtimeMinutes"), 92, 'exact starter matches receive curated runtime metadata');
assert.equal(evaluate("playlistRecords().find(movie => movie.title === 'Beetlejuice (1988)').moods.includes('light')"), true);
assert.equal(audios.every(audio => audio.playCount === 0), true, 'page load must not autoplay');

node('#history-toggle').dispatch('click');
assert.equal(node('#history').children.length, 17);
assert.equal(node('#history-toggle').textContent, 'Mostrar menos');
node('#history-toggle').dispatch('click');
assert.equal(node('#history').children.length, 5);

node('#language').value = 'en'; node('#language').dispatch('change');
assert.equal(sandbox.document.documentElement.lang, 'en');
assert.equal(JSON.parse(storage.get('cinema-roulette-v5')).language, 'en', 'language preference persists');
assert.equal(node('i18n:collectionTitle').textContent, 'Movies on the wheel');
assert.equal(node('#history-stats').textContent, '17 unique movies · 24 draws');
assert.equal(node('#history').children.length, 5, 'language switch preserves wall of fame view');
assert.equal(node('#theme').value, 'halloween');

node('#edit-toggle').dispatch('click');
assert.equal(node('#movie-editor').hidden, false);
node('#movies').value = 'Only one\nOnly one\n'; node('#movies').dispatch('input');
assert.equal(node('#count').textContent, 1); assert.equal(node('#eligible-count').textContent, 1); assert.equal(node('#spin').disabled, false);
const singleSpin = evaluate('spin()'); app.setNow(5000); animationFrames.shift()(5000);
assert.equal((await singleSpin).movie, 'Only one', 'a single eligible movie can be drawn');
assert.equal(node('#history-stats').textContent, '18 unique movies · 25 draws');
node('#movies').value = 'A\nB'; node('#movies').dispatch('input');
assert.equal(evaluate('movieList().length'), 2, 'duplicates are removed');
const originalMovies = node('#movies').value;
node('#reset').dispatch('click');
assert.equal(node('#count').textContent, 19, 'reset restores the original selection');
node('#movies').value = originalMovies; node('#movies').dispatch('input');
node('#finish-edit').dispatch('click');
assert.equal(node('#movie-editor').hidden, true);

node('#sound').dispatch('click');
assert.equal(node('#sound').getAttribute('aria-pressed'), 'false');
assert.equal(node('#sound').getAttribute('aria-label'), 'Turn sound on');
assert.equal(JSON.parse(storage.get('cinema-roulette-v5')).soundEnabled, false);
node('#sound').dispatch('click');
assert.equal(JSON.parse(storage.get('cinema-roulette-v5')).soundEnabled, true);
const pendingSpin = node('#spin').dispatch('click');
assert.equal(evaluate('spin({type: "click"})'), undefined, 'an event is not a movie pool');
const audioStarts = audios[0].playCount;
node('#spin').dispatch('click');
assert.equal(audios[0].playCount, audioStarts, 'repeated clicks cannot restart audio or create another draw');
assert.equal(animationFrames.length, 1);
assert.equal(audios[0].paused, false, 'roll sound starts during spin when enabled');
assert.equal(node('#movies').disabled, true); assert.equal(node('#reset').disabled, true);
node('#sound').dispatch('click');
assert.equal(audios.every(audio => audio.paused), true, 'disabling sound silences all audio immediately');
assert.equal(JSON.parse(storage.get('cinema-roulette-v5')).soundEnabled, false);
node('#sound').dispatch('click');
assert.equal(audios[0].paused, false, 'reenabling sound resumes the wheel while spinning');
assert.equal(node('#theme').disabled, true, 'theme cannot change in the middle of a spin');
app.setNow(10000); animationFrames.shift()(10000);
const result = await pendingSpin;
assert.equal(audios[1].playCount, 2, 'one ending chime per completed draw, including the preceding single-film draw');
assert.ok(['A', 'B'].includes(result.movie));
assert.equal(node('#result-title').textContent, result.movie);
assert.equal(JSON.parse(storage.get('cinema-roulette-v5')).themes.halloween.sessions.length, 2, 'each standard spin is recorded as a one-film session');
assert.equal(JSON.parse(storage.get('cinema-roulette-v5')).themes.halloween.sessions.at(-1).movies[0].id, result.id);
const titleBeforeLanguageChange = node('#result-title').textContent;
node('#language').value = 'pt-PT'; node('#language').dispatch('change');
assert.equal(node('#result-title').textContent, titleBeforeLanguageChange, 'language switch preserves selected movie');
assert.equal(node('#result-description').textContent, 'Apaga as luzes e carrega no play. Boa sessão!', 'language switch translates result instructions without changing the movie');
assert.equal(node('#result-label').textContent, 'O FILME DESTA NOITE', 'the completed result label follows the active language');
assert.equal(node('#hint').textContent, 'O destino escolheu. Agora só faltam as pipocas.');
assert.equal(node('#history-title').textContent, 'Mural da Fama');
assert.equal(node('#result').classList.contains('winner'), true);
assert.equal(node('#movies').disabled, false); assert.equal(node('#reset').disabled, false);
assert.equal(audios[0].paused, true);
assert.equal(audios[1].paused, false, 'ending chime plays after the spin when enabled');
const selectedByPointer = evaluate('Math.floor(((Math.PI * 2 - rotation) % (Math.PI * 2)) / (Math.PI * 2 / movieList().length))');
assert.equal(['A', 'B'][selectedByPointer], result.movie);
assert.equal(evaluate('winningIndex'), selectedByPointer, 'highlighted slice matches pointer and announcement');
const historyBeforeViewed = JSON.stringify(JSON.parse(storage.get('cinema-roulette-v5')).themes.halloween.history);
node('#watch-toggle').dispatch('click');
assert.equal(node('#watch-toggle').textContent, 'Desmarcar como visto');
const savedAfterViewed = JSON.parse(storage.get('cinema-roulette-v5'));
assert.equal(savedAfterViewed.themes.halloween.viewed.includes(result.id), true);
assert.equal(JSON.stringify(savedAfterViewed.themes.halloween.history), historyBeforeViewed, 'marking watched does not change draw history');
node('#watch-toggle').dispatch('click');
assert.equal(node('#watch-toggle').textContent, 'Marcar como visto', 'watched status can be undone');
assert.equal(JSON.parse(storage.get('cinema-roulette-v5')).themes.halloween.viewed.includes(result.id), false);
node('#watch-toggle').dispatch('click');
node('#avoid-viewed').checked = true; node('#avoid-viewed').dispatch('change');
assert.equal(node('#eligible-count').textContent, 1, 'the watched result is excluded from the eligible count');
assert.equal(node('#spin').disabled, false, 'one unwatched movie is still enough to spin');
const remainingSpin = evaluate('spin()'); app.setNow(15000); animationFrames.shift()(15000);
const remainingResult = await remainingSpin;
assert.notEqual(remainingResult.id, result.id, 'avoiding watched movies excludes the watched result');
node('#watch-toggle').dispatch('click');
assert.equal(node('#eligible-count').textContent, 0, 'all watched movies exhaust the opt-in pool');
assert.equal(node('#spin').disabled, true);
assert.equal(node('#exhausted-actions').hidden, false);
node('#include-viewed').dispatch('click');
assert.equal(node('#eligible-count').textContent, 2, 'including watched movies restores the full pool');
node('#avoid-viewed').checked = true; node('#avoid-viewed').dispatch('change');
node('#reset-viewed').dispatch('click');
assert.equal(node('#eligible-count').textContent, 2, 'reset watched list leaves the playlist intact');
assert.equal(JSON.stringify(JSON.parse(storage.get('cinema-roulette-v5')).themes.halloween.history) === historyBeforeViewed, false, 'only actual spins add to history');

node('#sound').dispatch('click');
assert.equal(audios.every(audio => audio.paused), true, 'turning sound off after the spin silences the chime');
node('#movies').value = Array.from({ length: 61 }, (_, i) => `Film ${i}`).join('\n'); node('#movies').dispatch('input');
assert.equal(node('#spin').disabled, true); assert.match(node('#list-status').textContent, /60/);
node('#movies').value = Array.from({ length: 60 }, (_, i) => `Film ${i}`).join('\n'); node('#movies').dispatch('input');
assert.equal(node('#spin').disabled, false);

// Theme state stays independent, including the curated Christmas starter list.
node('#theme').value = 'christmas'; node('#theme').dispatch('change');
assert.equal(node('#count').textContent, 13);
assert.equal(node('#history-stats').textContent, '0 filmes diferentes · 0 sorteios');
assert.equal(node('body').dataset.theme, 'christmas');
assert.equal(node('#brand-name').innerHTML, 'CHRISTMAS <b>ROULETTE</b>');
assert.equal(node('#wheel-theme-label').textContent, 'NATAL', 'Christmas wheel label is localized');
assert.equal(node('#movies').value.includes('Klaus (2019)'), true);
assert.equal(node('#catalog-results').children.length, 9, 'Christmas suggestions omit movies already on the wheel');
node('#catalog-search').value = 'Home Alone'; node('#catalog-search').dispatch('input');
assert.equal(node('#catalog-results').children.length, 2, 'offline title search distinguishes the two Home Alone films');
node('#catalog-search').value = 'Home Alone 1990'; node('#catalog-search').dispatch('input');
assert.equal(node('#catalog-results').children.length, 1, 'year in search narrows remake results');
const homeAloneCard = node('#catalog-results').children[0];
const homeAloneActions = homeAloneCard.children[1].children.at(-1);
assert.equal(homeAloneActions.children[0].disabled, true, 'films already in the playlist cannot be added twice');
node('#catalog-search').value = 'unlisted title'; node('#catalog-search').dispatch('input');
assert.equal(node('#catalog-results').children[0].textContent, 'Não foram encontradas sugestões nesta coleção.');
assert.equal(node('#catalog-results').children[0].selector, 'p');
node('#catalog-search').value = 'The Holiday'; node('#catalog-search').dispatch('input');
assert.equal(node('#catalog-results').children.length, 1);
const holiday = evaluate("CURATED_CATALOG.christmas.find(movie => movie.title === 'The Holiday (2006)')");
evaluate('addCatalogMovie(CURATED_CATALOG.christmas.find(movie => movie.title === \'The Holiday (2006)\'))');
assert.equal(node('#count').textContent, 14, 'curated catalogue movie can be added to the wheel');
assert.equal(evaluate('movieIsAdded(CURATED_CATALOG.christmas.find(movie => movie.title === \'The Holiday (2006)\'))'), true, 'newly added suggestion changes to already added state');
assert.equal(evaluate('playlistRecords().at(-1).source'), 'curated', 'local movie keeps a manual curation source');
assert.equal(holiday.tmdbRating, null, 'local catalogue does not invent a TMDB rating');
node('#movies').value = 'Holiday A (2000)\nHoliday B (2001)'; node('#movies').dispatch('input');
node('#theme').value = 'halloween'; node('#theme').dispatch('change');
assert.equal(node('#count').textContent, 60);
assert.equal(node('#history-stats').textContent, '20 filmes diferentes · 27 sorteios');
node('#theme').value = 'christmas'; node('#theme').dispatch('change');
assert.equal(node('#movies').value, 'Holiday A (2000)\nHoliday B (2001)');
assert.equal(node('#history-stats').textContent, '0 filmes diferentes · 0 sorteios');
assert.equal(JSON.parse(storage.get('cinema-roulette-v5')).activeTheme, 'christmas', 'theme preference persists');
const restoredTheme = await createApp(Object.fromEntries([...storage].map(([key, raw]) => [key, JSON.parse(raw)])));
assert.equal(restoredTheme.node('#theme').value, 'christmas');
assert.equal(restoredTheme.node('#language').value, 'pt-PT');
assert.equal(restoredTheme.node('#movies').value, 'Holiday A (2000)\nHoliday B (2001)');

const migrated = await createApp({ 'halloween-movies-v1': 'Persisted One\nPersisted Two', 'halloween-history-v1': { 'Persisted One': 9 }, 'halloween-sound-v1': false });
assert.equal(migrated.node('#movies').value, 'Persisted One\nPersisted Two');
assert.equal(migrated.node('#history-stats').textContent, '1 filme diferente · 9 sorteios');
assert.equal(migrated.node('#sound').getAttribute('aria-pressed'), 'false');
assert.equal(migrated.storage.has('halloween-movies-v1'), true, 'legacy data remains as a recoverable backup');
const migratedAgain = await createApp(Object.fromEntries([...migrated.storage].map(([key, raw]) => [key, JSON.parse(raw)])));
assert.equal(migratedAgain.node('#history-stats').textContent, '1 filme diferente · 9 sorteios', 'repeated migration does not duplicate counts');
assert.equal(migratedAgain.node('#movies').value, 'Persisted One\nPersisted Two');
const migratedV2 = await createApp({ 'cinema-roulette-v2': { version: 2, activeTheme: 'halloween', language: 'pt-PT', soundEnabled: true, themes: { halloween: { movies: 'Old A (1990)\nOld B (1991)', history: { 'Old A (1990)': 3 } }, christmas: { movies: 'New Year Film (2000)', history: {} } } } });
assert.equal(migratedV2.node('#history-stats').textContent, '1 filme diferente · 3 sorteios');
assert.deepEqual(JSON.parse(migratedV2.storage.get('cinema-roulette-v5')).themes.halloween.playlist.map(movie => movie.id), ['manual:old a (1990)', 'manual:old b (1991)']);
assert.equal(migratedV2.storage.has('cinema-roulette-v2'), true, 'version 2 remains recoverable after migration');
const migratedV3 = await createApp({ 'cinema-roulette-v3': { version: 3, activeTheme: 'halloween', language: 'en', soundEnabled: true, themes: { halloween: { playlist: [{ id: 'manual:beetlejuice (1988)', title: 'Beetlejuice (1988)' }, { id: 'manual:unknown (2026)', title: 'Unknown (2026)' }], history: { 'manual:beetlejuice (1988)': { id: 'manual:beetlejuice (1988)', title: 'Beetlejuice (1988)', count: 7 } }, viewed: [], avoidViewed: false }, christmas: { playlist: [{ id: 'manual:klaus (2019)', title: 'Klaus (2019)' }], history: {}, viewed: [], avoidViewed: false } } } });
assert.equal(migratedV3.node('#history-stats').textContent, '1 unique movie · 7 draws');
assert.equal(migratedV3.node('#count').textContent, 2);
assert.equal(JSON.parse(migratedV3.storage.get('cinema-roulette-v5')).themes.halloween.playlist[0].runtimeMinutes, 92, 'v3 migration attaches only an exact local title match');
assert.equal(JSON.parse(migratedV3.storage.get('cinema-roulette-v5')).themes.halloween.playlist[1].runtimeMinutes, null, 'unmatched manual movies keep unknown metadata');
assert.equal(migratedV3.storage.has('cinema-roulette-v3'), true, 'v3 remains recoverable after successful migration');
const migratedV3Again = await createApp(Object.fromEntries([...migratedV3.storage].map(([key, raw]) => [key, JSON.parse(raw)])));
assert.equal(migratedV3Again.node('#history-stats').textContent, '1 unique movie · 7 draws', 'migration from v3 remains idempotent');
const migratedV4 = await createApp({ 'cinema-roulette-v4': { version: 4, activeTheme: 'halloween', language: 'pt-PT', soundEnabled: false, themes: { halloween: { playlist: [{ id: 'manual:a (2020)', title: 'A (2020)' }], history: { 'manual:a (2020)': { id: 'manual:a (2020)', title: 'A (2020)', count: 5 } }, viewed: ['manual:a (2020)'], avoidViewed: true, filters: { moods: ['scary'], maxDuration: 90 } }, christmas: { playlist: [{ id: 'manual:b (2021)', title: 'B (2021)' }], history: {}, viewed: [], avoidViewed: false, filters: { moods: [], maxDuration: null } } } } });
const upgradedV4 = JSON.parse(migratedV4.storage.get('cinema-roulette-v5'));
assert.equal(upgradedV4.themes.halloween.history['manual:a (2020)'].count, 5, 'v4 migration preserves draw counts');
assert.deepEqual(upgradedV4.themes.halloween.viewed, ['manual:a (2020)']);
assert.deepEqual(upgradedV4.themes.halloween.filters, { moods: ['scary'], maxDuration: 90 });
assert.deepEqual(upgradedV4.themes.halloween.sessions, [], 'pre-session data migrates without invented sessions');
assert.equal(migratedV4.storage.has('cinema-roulette-v4'), true, 'v4 remains recoverable after migration');

const filteredApp = await createApp({ 'halloween-movies-v1': 'Beetlejuice (1988)\nHalloween (1978)\nOnly Unknown (2025)', 'halloween-history-v1': {} });
filteredApp.node('#filter-mood-scary').checked = true; filteredApp.node('#filter-mood-scary').dispatch('change');
assert.equal(filteredApp.node('#eligible-count').textContent, 1, 'mood filters keep only matching playlist records');
filteredApp.node('#filter-mood-scary').checked = false; filteredApp.node('#filter-mood-scary').dispatch('change');
filteredApp.node('#filter-duration').value = '90'; filteredApp.node('#filter-duration').dispatch('change');
assert.equal(filteredApp.node('#eligible-count').textContent, 0, 'a 90-minute filter excludes a 91-minute film');
assert.match(filteredApp.node('#filter-status').textContent, /sem duração conhecida/, 'unknown runtimes are explained when a time limit excludes them');
filteredApp.node('#metadata-movie').value = 'manual:only unknown (2025)'; filteredApp.node('#metadata-movie').dispatch('change');
filteredApp.node('#metadata-runtime').value = '80'; filteredApp.node('#metadata-mood-light').checked = true;
filteredApp.node('#save-metadata').dispatch('click');
assert.equal(vm.runInContext("playlistRecords().find(movie => movie.title === 'Only Unknown (2025)').runtimeMinutes", filteredApp.sandbox), 80, 'users can complete unknown runtime metadata');
assert.equal(filteredApp.node('#filter-status').textContent.includes('sem duração conhecida'), false, 'manual runtime removes the unknown-duration exclusion notice');
filteredApp.node('#filter-mood-scary').checked = false; filteredApp.node('#filter-mood-light').checked = true; filteredApp.node('#filter-mood-light').dispatch('change');
assert.equal(filteredApp.node('#eligible-count').textContent, 1, 'mood metadata makes a manually completed film eligible');
filteredApp.node('#surprise-mood').value = 'scary'; filteredApp.node('#surprise-duration').value = '90'; filteredApp.node('#surprise-mood').dispatch('change');
assert.equal(filteredApp.node('#surprise-submit').disabled, true, 'surprise session blocks criteria with no matching movies');
assert.equal(filteredApp.node('#surprise-discover').hidden, false, 'empty surprise pool offers movie discovery');
filteredApp.node('#surprise-mood').value = 'light'; filteredApp.node('#surprise-mood').dispatch('change');
assert.equal(filteredApp.node('#surprise-submit').disabled, false, 'surprise session enables when a matching movie exists');
const filteredPlaylistBeforeSurprise = filteredApp.node('#movies').value;
filteredApp.setReduceMotion(true); filteredApp.node('#surprise-submit').dispatch('click'); filteredApp.animationFrames.shift()(0);
assert.equal(filteredApp.node('#result-title').textContent, 'Only Unknown (2025)', 'surprise draw selects from the constrained pool');
assert.equal(filteredApp.node('#movies').value, filteredPlaylistBeforeSurprise, 'surprise draw does not replace or add to the playlist');
assert.equal(filteredApp.node('#history-stats').textContent, '1 filme diferente · 1 sorteio');
filteredApp.node('#clear-filters').dispatch('click');
assert.equal(filteredApp.node('#eligible-count').textContent, 3, 'clear filters restores all movies and includes viewed titles');
assert.equal(filteredApp.node('#filter-duration').value, 'any');
filteredApp.node('#language').value = 'en'; filteredApp.node('#language').dispatch('change');
assert.equal(filteredApp.node('i18n:filterTitle').textContent, 'Roulette filters');

const marathonApp = await createApp({ 'halloween-movies-v1': 'Marathon Film A (2020)\nMarathon Film B (2021)', 'halloween-history-v1': {} });
marathonApp.setReduceMotion(true);
marathonApp.node('#marathon-submit').dispatch('click');
assert.match(marathonApp.confirmMessage(), /Pediste 3 filmes, mas só há 2 elegíveis/,'a smaller eligible pool is explained before a marathon draw');
assert.equal(marathonApp.animationFrames.length, 0, 'declining the shorter-marathon confirmation does not draw');
assert.equal(marathonApp.node('#marathon-status').textContent, 'Sessão cancelada. Podes ajustar os filtros ou o número de filmes.');
marathonApp.setConfirm(true); marathonApp.node('#marathon-submit').dispatch('click'); marathonApp.animationFrames.shift()(0);
let marathonState = JSON.parse(marathonApp.storage.get('cinema-roulette-v5'));
let firstMarathon = marathonState.themes.halloween.sessions.at(-1);
assert.equal(firstMarathon.movies.length, 2, 'accepting the short-pool prompt draws every eligible film');
assert.equal(new Set(firstMarathon.movies.map(movie => movie.id)).size, 2, 'marathons do not repeat films');
assert.equal(marathonState.themes.halloween.history[firstMarathon.movies[0].id].count, 1);
assert.equal(marathonState.themes.halloween.history[firstMarathon.movies[1].id].count, 1, 'each marathon film is recorded exactly once');
assert.equal(marathonApp.node('#marathon-order').children.length, 2, 'ordered marathon results render as two entries');
assert.equal(marathonApp.node('#marathon-status').textContent, 'Sessão registada com 2 filmes elegíveis, em vez dos 3 pedidos.');
assert.equal(marathonApp.node('#marathon-total').textContent, 'Duração total incompleta: faltam durações conhecidas.');
assert.equal(marathonApp.node('#watch-toggle').hidden, true, 'individual marathon watch actions replace the single-result toggle');
const marathonHistoryBeforeWatch = JSON.stringify(marathonState.themes.halloween.history);
marathonApp.node('#marathon-order').children[0].children[1].dispatch('click');
marathonState = JSON.parse(marathonApp.storage.get('cinema-roulette-v5'));
assert.equal(JSON.stringify(marathonState.themes.halloween.history), marathonHistoryBeforeWatch, 'marking a marathon movie watched leaves Wall of Fame unchanged');
const currentSessionCountAfterWatch = marathonState.themes.halloween.sessions.at(-1).movies.length;
assert.equal(currentSessionCountAfterWatch, 2, 'marking a film watched does not edit session history');
marathonApp.node('#metadata-movie').value = firstMarathon.movies[0].id; marathonApp.node('#metadata-movie').dispatch('change');
marathonApp.node('#metadata-runtime').value = '80'; marathonApp.node('#save-metadata').dispatch('click');
marathonApp.node('#metadata-movie').value = firstMarathon.movies[1].id; marathonApp.node('#metadata-movie').dispatch('change');
marathonApp.node('#metadata-runtime').value = '95'; marathonApp.node('#save-metadata').dispatch('click');
marathonApp.node('#marathon-count').value = '2'; marathonApp.node('#marathon-count').dispatch('change'); marathonApp.node('#marathon-submit').dispatch('click'); marathonApp.animationFrames.shift()(0);
marathonState = JSON.parse(marathonApp.storage.get('cinema-roulette-v5'));
const secondMarathon = marathonState.themes.halloween.sessions.at(-1);
assert.equal(secondMarathon.movies.length, 2);
assert.equal(new Set(secondMarathon.movies.map(movie => movie.id)).size, 2);
assert.equal(marathonApp.node('#marathon-total').textContent, 'Duração total: 175 min.');
assert.equal(marathonApp.node('#session-history').children.length, 2, 'the separate session history retains the two ordered draws');
assert.equal(marathonState.themes.halloween.history[secondMarathon.movies[0].id].count, 2, 'each movie drawn in the next session increments Wall of Fame once');
marathonApp.node('#marathon-order').children[1].children[1].dispatch('click');
assert.equal(JSON.parse(marathonApp.storage.get('cinema-roulette-v5')).themes.halloween.sessions.length, 2, 'per-film watched toggles preserve session records');
marathonApp.node('#marathon-count').value = '1'; marathonApp.node('#marathon-count').dispatch('change'); marathonApp.node('#marathon-submit').dispatch('click'); marathonApp.animationFrames.shift()(0);
assert.equal(JSON.parse(marathonApp.storage.get('cinema-roulette-v5')).themes.halloween.sessions.at(-1).movies.length, 1, 'marathon panel can draw a one-film session');
const marathonThree = await createApp({ 'halloween-movies-v1': 'Three A (2020)\nThree B (2021)\nThree C (2022)', 'halloween-history-v1': {} });
marathonThree.setReduceMotion(true); marathonThree.node('#marathon-count').value = '3'; marathonThree.node('#marathon-submit').dispatch('click'); marathonThree.animationFrames.shift()(0);
const threeMovieSession = JSON.parse(marathonThree.storage.get('cinema-roulette-v5')).themes.halloween.sessions.at(-1);
assert.equal(threeMovieSession.movies.length, 3, 'marathon panel can draw a three-film session');
assert.equal(new Set(threeMovieSession.movies.map(movie => movie.id)).size, 3, 'three-film marathons also draw without repeats');
marathonApp.node('#theme').value = 'christmas'; marathonApp.node('#theme').dispatch('change');
assert.equal(marathonApp.node('#session-history').children.length, 0, 'session history is isolated by theme');
marathonApp.node('#theme').value = 'halloween'; marathonApp.node('#theme').dispatch('change');
assert.equal(marathonApp.node('#session-history').children.length, 3);

const emptyHistory = await createApp({ 'cinema-roulette-v2': { version: 2, activeTheme: 'halloween', language: 'pt-PT', soundEnabled: true, themes: { halloween: { movies: 'A\nB', history: {} }, christmas: { movies: 'C\nD', history: {} } } } });
assert.equal(emptyHistory.node('#history-stats').textContent, '0 filmes diferentes · 0 sorteios');
assert.equal(emptyHistory.node('#history').children.length, 1);
assert.equal(emptyHistory.node('#history-toggle').hidden, true);
const clearHistory = await createApp({ 'cinema-roulette-v2': { version: 2, activeTheme: 'halloween', language: 'pt-PT', soundEnabled: true, themes: { halloween: { movies: 'A\nB', history: { 'Film A': 2 } }, christmas: { movies: 'C\nD', history: {} } } } });
clearHistory.node('#clear-history').dispatch('click');
assert.equal(clearHistory.node('#history-stats').textContent, '1 filme diferente · 2 sorteios', 'declining confirmation preserves history');
clearHistory.setConfirm(true); clearHistory.node('#clear-history').dispatch('click');
assert.equal(clearHistory.node('#history-stats').textContent, '0 filmes diferentes · 0 sorteios', 'history clears only after confirmation');

const reducedMotion = await createApp();
reducedMotion.setReduceMotion(true);
const reducedSpin = vm.runInContext('spin()', reducedMotion.sandbox);
assert.equal(reducedMotion.animationFrames.length, 1);
reducedMotion.animationFrames.shift()(0);
assert.ok((await reducedSpin).movie);
assert.equal(reducedMotion.animationFrames.length, 0, 'reduced motion completes without animation frames');
const longTitles = ['A Very Long Full Movie Title That Must Remain Intact (2026)', 'Another Complete Movie Title (2025)'];
const longTitleApp = await createApp({ 'halloween-movies-v1': longTitles.join('\n') });
const longTitleSpin = vm.runInContext('spin()', longTitleApp.sandbox);
longTitleApp.setNow(5000); longTitleApp.animationFrames.shift()(5000);
const longTitleResult = await longTitleSpin;
assert.ok(longTitles.includes(longTitleResult.movie));
assert.equal(longTitleApp.node('#result-title').textContent, longTitleResult.movie, 'long selected title remains complete in the result');
assert.equal(longTitleApp.node('#movies').value, longTitles.join('\n'), 'editor keeps the complete movie titles');

const shareSource = await createApp({ 'halloween-movies-v1': 'Canção de Natal (2024)\nOther Film (2020)' });
shareSource.node('#generate-share').dispatch('click');
assert.equal(shareSource.node('#share-link-label').hidden, false, 'a short playlist generates a share URL');
const generatedShareUrl = new URL(shareSource.node('#share-link').value);
const generatedShare = JSON.parse(Buffer.from(generatedShareUrl.hash.slice('#playlist='.length), 'base64url').toString('utf8'));
assert.deepEqual(Object.keys(generatedShare).sort(), ['format', 'playlist', 'theme', 'version']);
assert.deepEqual(Object.keys(generatedShare.playlist[0]).sort(), ['title'], 'manual IDs are derived from the original title instead of repeating it in the URL');
assert.equal(generatedShare.playlist[0].title, 'Canção de Natal (2024)', 'share links preserve UTF-8 titles');
assert.equal(JSON.stringify(generatedShare).includes('history'), false);
assert.equal(JSON.stringify(generatedShare).includes('viewed'), false);
assert.equal(JSON.stringify(generatedShare).includes('language'), false);
assert.equal(shareSource.node('#copy-share-link').hidden, false);
await shareSource.node('#copy-share-link').dispatch('click');
assert.equal(shareSource.clipboardWrites[0], shareSource.node('#share-link').value, 'the copy action sends only the generated share URL to the clipboard');
shareSource.node('#language').value = 'en'; shareSource.node('#language').dispatch('change');
assert.equal(shareSource.node('#sharing-help').textContent, 'Create a link with the theme and playlist titles. It does not include history, watched movies, or preferences.', 'sharing instructions change language');

const christmasFirstTitle = vm.runInContext('CHRISTMAS_MOVIES[0]', shareSource.sandbox);
const christmasFirstId = vm.runInContext('manualId(CHRISTMAS_MOVIES[0])', shareSource.sandbox);
const sharedLinkPayload = { format: 'halloween-roulette-share', version: 1, theme: 'christmas', playlist: [{ id: christmasFirstId, title: christmasFirstTitle }, { id: 'manual:shared surprise film (2024)', title: 'Shared Surprise Film (2024)' }] };
const sharedLink = `https://joaopef.github.io/halloween-roulette/#playlist=${Buffer.from(JSON.stringify(sharedLinkPayload)).toString('base64url')}`;
const shareReceiver = await createApp({}, { location: { href: sharedLink } });
assert.equal(shareReceiver.node('#shared-preview').hidden, false, 'a valid link opens a preview');
assert.equal(shareReceiver.node('#import-shared').hidden, false);
assert.equal(shareReceiver.node('#count').textContent, 19, 'opening a link does not import automatically');
const christmasHistoryBeforeShare = JSON.stringify(JSON.parse(shareReceiver.storage.get('cinema-roulette-v5')).themes.christmas.history);
shareReceiver.node('#import-shared').dispatch('click');
let importedShareState = JSON.parse(shareReceiver.storage.get('cinema-roulette-v5'));
assert.equal(importedShareState.activeTheme, 'christmas');
assert.equal(importedShareState.themes.christmas.playlist.length, 14, 'shared entries merge into the existing theme collection');
assert.equal(importedShareState.themes.christmas.history[ importedShareState.themes.christmas.playlist[0].id ]?.count, undefined);
assert.equal(JSON.stringify(importedShareState.themes.christmas.history), christmasHistoryBeforeShare, 'share import preserves the Wall of Fame');
assert.match(shareReceiver.node('#shared-preview-status').textContent, /1 filmes adicionados; 1 duplicados ignorados/);

const malformedShare = { ...sharedLinkPayload, history: { secret: 9 } };
const invalidShareReceiver = await createApp({}, { location: { href: `https://joaopef.github.io/halloween-roulette/#playlist=${Buffer.from(JSON.stringify(malformedShare)).toString('base64url')}` } });
assert.equal(invalidShareReceiver.node('#shared-preview').hidden, false);
assert.equal(invalidShareReceiver.node('#import-shared').hidden, true, 'invalid share payloads cannot be imported');
assert.match(invalidShareReceiver.node('#shared-preview-summary').textContent, /inválido/);
assert.equal(invalidShareReceiver.node('#count').textContent, 19);
const invalidEncodingReceiver = await createApp({}, { location: { href: 'https://joaopef.github.io/halloween-roulette/#playlist=not!base64' } });
assert.equal(invalidEncodingReceiver.node('#import-shared').hidden, true, 'invalid share encodings are rejected before import');
const shareOverflowPayload = { format: 'halloween-roulette-share', version: 1, theme: 'halloween', playlist: Array.from({ length: 60 }, (_, index) => ({ title: `Shared Overflow Film ${index} (2024)` })) };
const shareOverflowReceiver = await createApp({}, { location: { href: `https://joaopef.github.io/halloween-roulette/#playlist=${Buffer.from(JSON.stringify(shareOverflowPayload)).toString('base64url')}` } });
const shareOverflowBefore = shareOverflowReceiver.storage.get('cinema-roulette-v5');
shareOverflowReceiver.node('#import-shared').dispatch('click');
assert.match(shareOverflowReceiver.node('#shared-preview-status').textContent, /excederia o limite de 60 filmes/);
assert.equal(shareOverflowReceiver.storage.get('cinema-roulette-v5'), shareOverflowBefore, 'an over-limit share import preserves the existing collection');
const longShareTitles = Array.from({ length: 6 }, (_, index) => `${String(index).padStart(2, '0')} ${'A'.repeat(480)}`);
const tooLongShare = await createApp({ 'halloween-movies-v1': longShareTitles.join('\n') });
tooLongShare.node('#generate-share').dispatch('click');
assert.equal(tooLongShare.node('#share-link-label').hidden, true);
assert.equal(tooLongShare.node('#share-file-download').hidden, false, 'large playlists offer a JSON file instead of a huge URL');
assert.equal(tooLongShare.node('#share-status').textContent, 'A playlist é demasiado grande para um link curto. Exporta o ficheiro JSON da playlist.');
tooLongShare.node('#share-file-download').dispatch('click');
assert.equal(tooLongShare.downloadNames.at(-1), 'halloween-roulette-halloween-playlist.json');
assert.equal(JSON.parse(await tooLongShare.downloads.at(-1).text()).format, 'halloween-roulette-playlist', 'large share lists download as a portable playlist file');

const portableSource = await createApp();
const exportedPlaylist = JSON.parse(JSON.stringify(vm.runInContext("playlistFilePayload('christmas')", portableSource.sandbox)));
assert.equal(exportedPlaylist.format, 'halloween-roulette-playlist');
assert.equal(vm.runInContext('validatePlaylistPayload(playlistFilePayload("christmas")).playlist.length', portableSource.sandbox), 13, 'exported curated movies pass their documented playlist schema');
assert.equal('history' in exportedPlaylist, false, 'playlist exports exclude history');
portableSource.node('#portability-theme').value = 'christmas';
portableSource.node('#export-playlist').dispatch('click');
assert.equal(portableSource.downloadNames.at(-1), 'halloween-roulette-christmas-playlist.json');
assert.equal(JSON.parse(await portableSource.downloads.at(-1).text()).playlist.length, 13, 'playlist export creates a JSON download');
portableSource.node('#export-backup').dispatch('click');
assert.equal(portableSource.downloadNames.at(-1), 'halloween-roulette-backup.json');
assert.equal(JSON.parse(await portableSource.downloads.at(-1).text()).format, 'halloween-roulette-backup', 'backup export creates a separate JSON download');
const portableNewMovie = { id: 'manual:shared portable film (2022)', title: 'Shared Portable Film (2022)' };
const portableImport = { format: 'halloween-roulette-playlist', version: 1, theme: 'christmas', playlist: [{ id: christmasFirstId, title: christmasFirstTitle }, portableNewMovie] };
assert.equal(vm.runInContext(`validatePlaylistPayload(${JSON.stringify(portableImport)}) !== null`, portableSource.sandbox), true);
assert.equal(vm.runInContext(`validatePlaylistPayload(${JSON.stringify({ ...portableImport, playlist: [{ id: 'manual:forged', title: 'Different title' }] })}) === null`, portableSource.sandbox), true, 'playlist import rejects IDs which do not match the title or TMDB ID');
const portableTarget = await createApp();
const portableStorageBefore = portableTarget.storage.get('cinema-roulette-v5');
portableTarget.node('#playlist-file-input').files = [{ size: JSON.stringify(portableImport).length, text: async () => JSON.stringify(portableImport) }];
await portableTarget.node('#playlist-file-input').dispatch('change');
assert.equal(portableTarget.node('#playlist-import-preview').hidden, false, 'playlist files show a preview before changes');
assert.equal(portableTarget.storage.get('cinema-roulette-v5'), portableStorageBefore, 'previewing a playlist file does not change local data');
portableTarget.node('#language').value = 'en'; portableTarget.node('#language').dispatch('change');
assert.match(portableTarget.node('#playlist-import-summary').textContent, /movies · Add movies without duplicates/, 'file preview follows the selected interface language');
portableTarget.node('#language').value = 'pt-PT'; portableTarget.node('#language').dispatch('change');
portableTarget.node('#apply-playlist-import').dispatch('click');
let portableState = JSON.parse(portableTarget.storage.get('cinema-roulette-v5'));
assert.equal(portableState.activeTheme, 'christmas');
assert.equal(portableState.themes.christmas.playlist.length, 14);
assert.match(portableTarget.node('#portability-status').textContent, /1 filmes importados; 1 duplicados ignorados/);
const invalidPlaylistTarget = await createApp();
invalidPlaylistTarget.node('#playlist-file-input').files = [{ size: 30, text: async () => '{"version":99}' }];
await invalidPlaylistTarget.node('#playlist-file-input').dispatch('change');
assert.equal(invalidPlaylistTarget.node('#playlist-import-preview').hidden, true);
assert.match(invalidPlaylistTarget.node('#portability-status').textContent, /inválido/);
const limitPlaylistTarget = await createApp();
const oversizedPlaylistPayload = { format: 'halloween-roulette-playlist', version: 1, theme: 'halloween', playlist: Array.from({ length: 42 }, (_, index) => ({ id: `manual:imported film ${index} (2024)`, title: `Imported Film ${index} (2024)` })) };
limitPlaylistTarget.node('#playlist-file-input').files = [{ size: JSON.stringify(oversizedPlaylistPayload).length, text: async () => JSON.stringify(oversizedPlaylistPayload) }];
await limitPlaylistTarget.node('#playlist-file-input').dispatch('change');
limitPlaylistTarget.node('#apply-playlist-import').dispatch('click');
assert.match(limitPlaylistTarget.node('#portability-status').textContent, /limite de 60 filmes/);
assert.equal(JSON.parse(limitPlaylistTarget.storage.get('cinema-roulette-v5')).themes.halloween.playlist.length, 19, 'a merge over the limit leaves the collection intact');

const backupSource = await createApp();
backupSource.setReduceMotion(true);
let backupSpin = vm.runInContext('spin()', backupSource.sandbox); backupSource.animationFrames.shift()(0); await backupSpin;
vm.runInContext('setWatched(lastResultMovieId, true)', backupSource.sandbox);
backupSource.node('#language').value = 'en'; backupSource.node('#language').dispatch('change');
backupSource.node('#theme').value = 'christmas'; backupSource.node('#theme').dispatch('change');
backupSpin = vm.runInContext('spin()', backupSource.sandbox); backupSource.animationFrames.shift()(0); await backupSpin;
vm.runInContext('setWatched(lastResultMovieId, true)', backupSource.sandbox);
const backupExport = JSON.parse(JSON.stringify(vm.runInContext('backupPayload()', backupSource.sandbox)));
const replaceTarget = await createApp({ 'cinema-roulette-v5': backupExport.data });
const replaceBefore = JSON.parse(replaceTarget.storage.get('cinema-roulette-v5'));
const replacementPlaylist = { format: 'halloween-roulette-playlist', version: 1, theme: 'christmas', playlist: [{ id: 'manual:replacement film (2025)', title: 'Replacement Film (2025)' }] };
replaceTarget.node('#playlist-import-mode').value = 'replace';
replaceTarget.node('#playlist-file-input').files = [{ size: JSON.stringify(replacementPlaylist).length, text: async () => JSON.stringify(replacementPlaylist) }];
await replaceTarget.node('#playlist-file-input').dispatch('change');
assert.equal(replaceTarget.node('#playlist-import-preview').hidden, false, 'replacement still shows a preview before confirmation');
replaceTarget.node('#apply-playlist-import').dispatch('click');
assert.match(replaceTarget.confirmMessage(), /Replace the Christmas playlist/);
let replaceState = JSON.parse(replaceTarget.storage.get('cinema-roulette-v5'));
assert.equal(replaceState.themes.christmas.playlist.length, replaceBefore.themes.christmas.playlist.length, 'declining replacement leaves the playlist unchanged');
assert.deepEqual(replaceState.themes.christmas.history, replaceBefore.themes.christmas.history, 'declining replacement preserves draw history');
replaceTarget.setConfirm(true); replaceTarget.node('#apply-playlist-import').dispatch('click');
replaceState = JSON.parse(replaceTarget.storage.get('cinema-roulette-v5'));
assert.equal(replaceState.themes.christmas.playlist.length, 1, 'confirmed replacement changes only the selected playlist');
assert.deepEqual(replaceState.themes.christmas.history, replaceBefore.themes.christmas.history, 'playlist replacement preserves the Wall of Fame');
assert.deepEqual(replaceState.themes.christmas.viewed, replaceBefore.themes.christmas.viewed, 'playlist replacement preserves viewed status');
assert.equal(backupExport.format, 'halloween-roulette-backup');
assert.equal(backupExport.data.version, 5);
assert.equal(backupExport.data.language, 'en');
assert.equal(Object.values(backupExport.data.themes.halloween.history).reduce((sum, entry) => sum + entry.count, 0), 25, 'the backup retains prior draw counts and the new draw');
assert.equal(backupExport.data.themes.halloween.viewed.length, 1);
assert.equal(backupExport.data.themes.christmas.viewed.length, 1);
assert.equal(vm.runInContext(`validateBackupPayload(${JSON.stringify(backupExport)}) !== null`, backupSource.sandbox), true, 'a full backup round-trips through its validator');
const backupTarget = await createApp();
const backupStorageBefore = backupTarget.storage.get('cinema-roulette-v5');
backupTarget.node('#backup-file-input').files = [{ size: JSON.stringify(backupExport).length, text: async () => JSON.stringify(backupExport) }];
await backupTarget.node('#backup-file-input').dispatch('change');
assert.equal(backupTarget.node('#backup-import-preview').hidden, false);
assert.equal(backupTarget.storage.get('cinema-roulette-v5'), backupStorageBefore, 'a backup preview does not overwrite local data');
backupTarget.node('#apply-backup-import').dispatch('click');
assert.match(backupTarget.confirmMessage(), /Substituir os dados locais/);
assert.equal(backupTarget.storage.get('cinema-roulette-v5'), backupStorageBefore, 'declining a backup restore preserves local data');
backupTarget.setConfirm(true); backupTarget.node('#apply-backup-import').dispatch('click');
const restoredState = JSON.parse(backupTarget.storage.get('cinema-roulette-v5'));
assert.equal(restoredState.activeTheme, 'christmas');
assert.equal(restoredState.language, 'en', 'backup restore applies saved global language preference');
assert.equal(restoredState.themes.halloween.viewed.length, 1);
assert.equal(restoredState.themes.christmas.history[Object.keys(restoredState.themes.christmas.history)[0]].count, 1);
assert.match(backupTarget.node('#portability-status').textContent, /Backup restored/);
const oversizedBackupTarget = await createApp();
oversizedBackupTarget.node('#backup-file-input').files = [{ size: 2_000_001, text: async () => '{}' }];
await oversizedBackupTarget.node('#backup-file-input').dispatch('change');
assert.match(oversizedBackupTarget.node('#portability-status').textContent, /2 MB/);
const invalidBackupTarget = await createApp();
const invalidBackupBefore = invalidBackupTarget.storage.get('cinema-roulette-v5');
invalidBackupTarget.node('#backup-file-input').files = [{ size: 70, text: async () => JSON.stringify({ format: 'halloween-roulette-backup', version: 1, data: { version: 5, activeTheme: 'halloween' } }) }];
await invalidBackupTarget.node('#backup-file-input').dispatch('change');
assert.equal(invalidBackupTarget.node('#backup-import-preview').hidden, true);
assert.match(invalidBackupTarget.node('#portability-status').textContent, /inválida ou incompatível/);
assert.equal(invalidBackupTarget.storage.get('cinema-roulette-v5'), invalidBackupBefore, 'invalid backups never alter local data');

const tmdbConfig = { CINEMA_CATALOG_PROXY_URL: 'https://catalog.example/api/3/', CINEMA_TMDB_LOGO_URL: 'https://assets.example/tmdb-approved.svg' };
const tmdbCalls = [];
const onlineCatalog = await createApp({}, { window: tmdbConfig, fetch: async (url, requestOptions) => {
  const parsed = new URL(url); tmdbCalls.push({ url: parsed.href, requestOptions });
  if (parsed.pathname.endsWith('/search/movie')) return { ok: true, json: async () => ({ results: [{ id: 123, title: 'Localized Film', original_title: 'Original Film', release_date: '2020-01-02', poster_path: '/poster.jpg', vote_average: 7.2, overview: 'Search overview' }] }) };
  if (parsed.pathname.endsWith('/movie/123')) return { ok: true, json: async () => ({ id: 123, title: 'Localized Film', original_title: 'Original Film', release_date: '2020-01-02', runtime: 95, genres: [{ name: 'Comedy' }], poster_path: '/poster.jpg', vote_average: 7.6, overview: 'Detailed overview', external_ids: { imdb_id: 'tt1234567' } }) };
  if (parsed.pathname.endsWith('/movie/123/recommendations')) return { ok: true, json: async () => ({ results: [{ id: 123, title: 'Original Film', original_title: 'Original Film', release_date: '2020-01-02' }, { id: 456, title: 'Related Film', original_title: 'Related Film', release_date: '1980-05-01', vote_average: 6.5, overview: 'A haunted story.', genre_ids: [27] }] }) };
  if (parsed.pathname.endsWith('/recommendations')) return { ok: true, json: async () => ({ results: [] }) };
  throw new Error(`Unexpected TMDB request: ${parsed.pathname}`);
} });
onlineCatalog.node('#catalog-search').value = 'Original Film 2020';
await onlineCatalog.node('#catalog-search-form').dispatch('submit');
assert.equal(onlineCatalog.node('#catalog-results').children.length, 1, 'TMDB search shows its returned title');
assert.equal(onlineCatalog.node('#catalog-status').textContent, '1 resultados de pesquisa TMDB.');
assert.equal(onlineCatalog.node('#tmdb-attribution').hidden, false, 'configured TMDB data reveals its attribution notice and supplied logo');
assert.equal(vm.runInContext('remoteSearchResults[0].id', onlineCatalog.sandbox), 'tmdb:123');
assert.equal(vm.runInContext('remoteSearchResults[0].runtimeMinutes', onlineCatalog.sandbox), 95);
assert.equal(vm.runInContext('remoteSearchResults[0].imdbId', onlineCatalog.sandbox), 'tt1234567');
assert.equal(vm.runInContext('remoteSearchResults[0].tmdbRating', onlineCatalog.sandbox), 7.6);
assert.equal(vm.runInContext('remoteSearchResults[0].posterUrl', onlineCatalog.sandbox), 'https://image.tmdb.org/t/p/w342/poster.jpg');
assert.equal(tmdbCalls.every(request => !request.url.includes('api_key') && !request.url.includes('token') && !request.requestOptions.headers.Authorization), true, 'the browser never receives a TMDB credential');
vm.runInContext('addCatalogMovie(remoteSearchResults[0])', onlineCatalog.sandbox);
assert.equal(onlineCatalog.node('#count').textContent, 20);
assert.equal(vm.runInContext('playlistRecords().at(-1).tmdbId', onlineCatalog.sandbox), 123);
await vm.runInContext('loadRelatedRecommendations()', onlineCatalog.sandbox);
assert.equal(onlineCatalog.node('#related-results').children.length, 1, 'related results omit a film already on the wheel');
assert.equal(vm.runInContext('relatedResults.children[0].children[1].children[0].textContent', onlineCatalog.sandbox), 'Related Film');
assert.equal(vm.runInContext("movieIsAdded({title:'HÓCUS   PÓCUS', tmdbId:10439})", onlineCatalog.sandbox), true, 'title without a year and accents matches the existing film');
assert.equal(vm.runInContext("movieIsAdded({title:'Dont Look Under the Bed (1999)'})", onlineCatalog.sandbox), true, 'apostrophes do not produce duplicate recommendations');
assert.equal(vm.runInContext("movieIsAdded({title:'Abracadabra (1993)', tmdbId:10439})", onlineCatalog.sandbox), true, 'verified TMDB identity also matches translated titles');
assert.equal(evaluate("sameMovieTitle({title:'Halloween (1978)'},{title:'Halloween (2018)'})"), false, 'different remakes remain distinct');
assert.equal(evaluate("halloweenRecommendation({title:'Family camping', genres:['Family'], overview:{en:'A summer sports holiday'}})"), false);
assert.equal(evaluate("halloweenRecommendation({title:'Spooky house', genres:['Family'], overview:{en:'A haunted house with ghosts'}})"), true);
const extendedCatalog = await createApp({}, { window: tmdbConfig, fetch: async url => {
  const seed = Number(new URL(url).pathname.match(/movie\/(\d+)/)?.[1]);
  return { ok: true, json: async () => ({ results: [
    { id:10439, original_title:'Hocus Pocus', title:'Hocus Pocus', release_date:'1993-07-16', genre_ids:[14,10751], overview:'Witches at Halloween' },
    { id:999999, title:'Sports family', genre_ids:[10751], overview:'A summer holiday' },
    { id:999998, title:'Unrelated fantasy', genre_ids:[14], overview:'An adventure in space' },
    ...Array.from({length:20}, (_,i)=>({id:seed*100+i, title:`Horror ${seed}-${i}`, release_date:'2020-01-01', genre_ids:[27], overview:'A scary story'}))
  ]}) };
} });
await vm.runInContext('loadRelatedRecommendations()', extendedCatalog.sandbox);
assert.equal(extendedCatalog.node('#related-results').children.length,16);
assert.equal(vm.runInContext('relatedCache.movies.some(movie=>movie.tmdbId===10439 || movie.tmdbId===999999 || movie.tmdbId===999998)',extendedCatalog.sandbox),false,'existing titles and unrelated family/fantasy films are excluded');
await extendedCatalog.node('#related-more').dispatch('click');
assert.equal(extendedCatalog.node('#related-results').children.length,32,'more recommendations exposes another batch without the old eight-film limit');
vm.runInContext('addCatalogMovie(relatedCache.movies[0])',extendedCatalog.sandbox);
assert.equal(vm.runInContext('relatedResults.children.some(card=>card.children[1].children[0].textContent===displayTitle(relatedCache.movies[0]))',extendedCatalog.sandbox),false,'adding a recommendation immediately removes its card');

const noResultCatalog = await createApp({}, { window: tmdbConfig, fetch: async () => ({ ok: true, json: async () => ({ results: [] }) }) });
noResultCatalog.node('#catalog-search').value = 'No such film';
await noResultCatalog.node('#catalog-search-form').dispatch('submit');
assert.equal(noResultCatalog.node('#catalog-results').children[0].textContent, 'A pesquisa TMDB não encontrou filmes.');
const failedCatalog = await createApp({}, { window: tmdbConfig, fetch: async () => { throw new TypeError('network offline'); } });
failedCatalog.node('#catalog-search').value = 'Beetlejuice';
await failedCatalog.node('#catalog-search-form').dispatch('submit');
assert.equal(failedCatalog.node('#catalog-status').textContent, 'Não foi possível contactar o catálogo TMDB. A mostrar as sugestões locais.');
assert.equal(failedCatalog.node('#catalog-results').children.length, 1, 'network failure falls back to local curation');

const html = await readFile('index.html', 'utf8');
const css = await readFile('style.css', 'utf8');
assert.match(html, /Mural da Fama/); assert.match(html, /aria-live="polite"/); assert.match(html, /<svg/);
assert.match(css, /:focus-visible/); assert.match(css, /prefers-reduced-motion:reduce/); assert.match(css, /min-width:44px/);

const allowedOrigin = 'https://joaopef.github.io';
const requestToProxy = (path, { origin = allowedOrigin, method = 'GET', headers = {} } = {}) => new Request(`https://catalog.example/3/${path}`, { method, headers: { Origin: origin, ...headers } });
const unauthenticated = await tmdbProxy.fetch(requestToProxy('search/movie'), {});
assert.equal(unauthenticated.status, 503, 'missing TMDB credentials disable online mode safely');
const deniedOrigin = await tmdbProxy.fetch(requestToProxy('search/movie', { origin: 'https://attacker.example' }), { TMDB_API_READ_ACCESS_TOKEN: 'secret' });
assert.equal(deniedOrigin.status, 403, 'proxy rejects unknown browser origins');
const preflight = await tmdbProxy.fetch(requestToProxy('search/movie', { method: 'OPTIONS' }), {});
assert.equal(preflight.status, 204, 'proxy responds to browser preflight without credentials');
assert.equal(preflight.headers.get('Access-Control-Allow-Origin'), allowedOrigin);
const proxyNoQuery = await tmdbProxy.fetch(requestToProxy('search/movie'), { TMDB_API_READ_ACCESS_TOKEN: 'secret', RATE_LIMITER: {} });
assert.equal(proxyNoQuery.status, 400, 'proxy validates required search parameters');
const proxyDeniedRoute = await tmdbProxy.fetch(requestToProxy('configuration'), { TMDB_API_READ_ACCESS_TOKEN: 'secret', RATE_LIMITER: {} });
assert.equal(proxyDeniedRoute.status, 404, 'proxy only exposes the documented TMDB routes');
const passedRateLimiter = { idFromName: name => name, get: name => ({ async fetch() { assert.match(name, /^[a-f0-9]{64}$/); return new Response('OK'); } }) };
const originalFetch = globalThis.fetch;
let upstreamRequest;
try {
  globalThis.fetch = async (url, init) => { upstreamRequest = { url: new URL(url), init }; return new Response(JSON.stringify({ results: [] }), { headers: { 'Content-Type': 'application/json' } }); };
  const proxySearch = await tmdbProxy.fetch(requestToProxy('search/movie?query=The%20Thing&language=en-US&primary_release_year=1982', { headers: { 'CF-Connecting-IP': '203.0.113.10' } }), { TMDB_API_READ_ACCESS_TOKEN: 'secret-token-for-server', RATE_LIMITER: passedRateLimiter });
  assert.equal(proxySearch.status, 200);
  assert.equal(proxySearch.headers.get('Access-Control-Allow-Origin'), allowedOrigin);
  assert.equal(upstreamRequest.url.hostname, 'api.themoviedb.org');
  assert.equal(upstreamRequest.url.searchParams.get('query'), 'The Thing');
  assert.equal(upstreamRequest.url.searchParams.get('primary_release_year'), '1982');
  assert.equal(upstreamRequest.url.searchParams.has('api_key'), false);
  assert.equal(upstreamRequest.init.headers.Authorization, 'Bearer secret-token-for-server', 'server token is sent only from the Worker to TMDB');
  assert.equal(await proxySearch.text(), '{"results":[]}');
} finally { globalThis.fetch = originalFetch; }

const rows = new Map();
const limiterState = { storage: { async transaction(operation) { return operation({ get: async key => rows.get(key), put: async (key, value) => rows.set(key, value) }); } } };
const rateLimiter = new CinemaRateLimiter(limiterState);
for (let index = 0; index < 90; index++) assert.equal((await rateLimiter.fetch(new Request('https://rate-limit.internal/check', { method: 'POST' }))).status, 200);
const limited = await rateLimiter.fetch(new Request('https://rate-limit.internal/check', { method: 'POST' }));
assert.equal(limited.status, 429, 'atomic limiter rejects the 91st request in a minute');
assert.ok(Number(limited.headers.get('Retry-After')) > 0);
for (const count of [1, 2, 3, 9]) {
  const modeApp = await createApp();
  modeApp.setReduceMotion(true);
  modeApp.node('#movies').value = Array.from({ length: count }, (_, index) => index === 0 ? 'A very long title for a manually added movie with no poster' : `Film ${index}`).join('\n');
  modeApp.node('#movies').dispatch('input');
  modeApp.node('#draw-mode').value = 'doors'; modeApp.node('#draw-mode').dispatch('change');
  modeApp.node('#draw-pace').value = 'suspense'; modeApp.node('#draw-pace').dispatch('change');
  assert.equal(JSON.parse(modeApp.storage.get('cinema-roulette-v5')).themes.halloween.drawMode, 'doors', 'draw mode preference persists for Halloween');
  assert.equal(JSON.parse(modeApp.storage.get('cinema-roulette-v5')).themes.halloween.drawPace, 'suspense', 'draw pace preference persists for Halloween');
  const reloadedModeApp = await createApp({ 'cinema-roulette-v5': JSON.parse(modeApp.storage.get('cinema-roulette-v5')) });
  assert.equal(reloadedModeApp.node('#draw-mode').value, 'doors', 'draw mode survives a reload');
  assert.equal(reloadedModeApp.node('#draw-pace').value, 'suspense', 'draw pace survives a reload');
  modeApp.node('#spin').dispatch('click');
  const doors = modeApp.node('#doors').children;
  assert.equal(doors.length, Math.min(3, count), 'mystery doors only show available distinct movies');
  assert.equal(new Set(vm.runInContext('doorCandidates.map(movie => movie.id)', modeApp.sandbox)).size, Math.min(3, count), 'doors never repeat a movie in the same round');
  const historyBeforeDoors = JSON.stringify(vm.runInContext('history', modeApp.sandbox));
  assert.equal(JSON.stringify(vm.runInContext('history', modeApp.sandbox)), historyBeforeDoors, 'preparing mystery doors does not record a draw');
  const reveal = doors[0].dispatch('click');
  assert.equal(modeApp.audios[0].playCount, 0, 'doors never start the wheel sound');
  assert.equal(modeApp.audios.slice(2).reduce((total, audio) => total + audio.playCount, 0), 1, 'one creature effect starts on opening a door');
  modeApp.animationFrames.shift()(0);
  const picked = await reveal;
  assert.equal(modeApp.node('#result-title').textContent, picked.movie, 'door result card matches the drawn title');
  assert.ok(modeApp.node('#spin').innerHTML.includes('Escolher outra porta'));
  assert.equal(vm.runInContext('themeData.sessions.length', modeApp.sandbox), 1, 'opening a door records exactly one result');
  assert.equal(doors[0].getAttribute('aria-label').includes(picked.movie), true, 'the selected door reveals its title');
  assert.equal(doors[0].children.some(child => child.textContent === picked.movie), true, 'the selected door shows the movie title visually');
  assert.equal(modeApp.audios[1].playCount, 0, 'doors do not play the wheel completion ding');
  assert.equal(doors.slice(1).some(door => door.getAttribute('aria-label').includes(picked.movie)), false, 'other doors stay closed without revealing a title');
  assert.equal(vm.runInContext('themeData.sessions.at(-1).movies[0].id', modeApp.sandbox), picked.id, 'door result and session history use the same movie');
}
const shuffleApp = await createApp();
shuffleApp.setReduceMotion(true);
shuffleApp.node('#movies').value = 'A Manual Film Without Any Poster Data'; shuffleApp.node('#movies').dispatch('input');
shuffleApp.node('#draw-mode').value = 'shuffle'; shuffleApp.node('#draw-mode').dispatch('change');
assert.equal(shuffleApp.node('#wheel').selector, '#wheel');
assert.equal(shuffleApp.node('#shuffle-stage').hidden, false, 'title shuffle stage is shown without poster metadata');
const shuffleResult = shuffleApp.sandbox && shuffleApp.node('#spin').dispatch('click');
shuffleApp.animationFrames.shift()(0);
const shuffled = await shuffleResult;
assert.equal(shuffleApp.node('#result-title').textContent, shuffled.movie, 'title shuffle reveals the selected movie in the shared result card');
assert.equal(shuffleApp.node('#shuffle-ticker').children.length, 1, 'the final title is a single centred row');
assert.equal(shuffleApp.node('#shuffle-ticker').children[0].textContent, shuffled.movie);
assert.equal(shuffleApp.node('#shuffle-ticker').style.transform, 'translateY(-50%)');
assert.ok(shuffleApp.node('#spin').innerHTML.includes('Sortear outro filme'));
assert.equal(vm.runInContext('themeData.sessions.length', shuffleApp.sandbox), 1, 'title shuffle records exactly once');
for (const mode of ['wheel', 'shuffle', 'posters']) for (const count of [1, 2, 3, 9]) {
  const drawApp = await createApp(); drawApp.setReduceMotion(true);
  drawApp.node('#movies').value = Array.from({ length: count }, (_, index) => `Manual title ${index + 1} with possible missing artwork`).join('\n');
  drawApp.node('#movies').dispatch('input');
  drawApp.node('#draw-mode').value = mode; drawApp.node('#draw-mode').dispatch('change');
  const pendingDraw = drawApp.node('#spin').dispatch('click'); drawApp.animationFrames.shift()(0);
  const outcome = await pendingDraw;
  assert.equal(drawApp.node('#result-title').textContent, outcome.movie, `${mode} result matches the selected movie with ${count} eligible`);
  if (mode === 'posters') {
    assert.equal(drawApp.node('#poster-strip').children.length, 1, 'poster shuffle leaves one winning poster');
    assert.equal(drawApp.node('#poster-strip').children[0].dataset.movieId, outcome.id, 'winning artwork matches the recorded movie, including missing posters');
  }
  assert.equal(vm.runInContext('themeData.sessions.at(-1).movies.length', drawApp.sandbox), 1, `${mode} records one movie with ${count} eligible`);
}
const animatedPosters = await createApp();
animatedPosters.node('#draw-mode').value = 'posters'; animatedPosters.node('#draw-mode').dispatch('change');
const posterDraw = animatedPosters.node('#spin').dispatch('click');
animatedPosters.animationFrames.shift()(700);
assert.equal(animatedPosters.node('#poster-strip').children.length, 3, 'normal motion shows three poster tiles during the draw');
animatedPosters.animationFrames.shift()(1500);
const posterWinner = await posterDraw;
assert.equal(animatedPosters.node('#poster-strip').children[0].dataset.movieId, posterWinner.id);
assert.equal(animatedPosters.node('#poster-strip').children[0].children[0].children[1].src.startsWith('https://image.tmdb.org/'), true, 'starter winner uses a TMDB poster');
const restoredPosters = await createApp(Object.fromEntries([...animatedPosters.storage].map(([key, raw]) => [key, JSON.parse(raw)])));
assert.equal(restoredPosters.node('#draw-mode').value, 'posters', 'poster mode survives reload');
const mutedDoors = await createApp();
mutedDoors.node('#draw-mode').value = 'doors'; mutedDoors.node('#draw-mode').dispatch('change');
mutedDoors.node('#spin').dispatch('click');
const mutedDoorDraw = mutedDoors.node('#doors').children[0].dispatch('click');
mutedDoors.node('#sound').dispatch('click');
assert.equal(mutedDoors.audios.every(audio => audio.paused), true, 'mute immediately stops every door and wheel sound');
mutedDoors.animationFrames.shift()(1500); await mutedDoorDraw;
assert.equal(mutedDoors.audios[1].playCount, 0, 'muted door result remains silent');
const noMatchesApp = await createApp();
noMatchesApp.node('#movies').value = 'A Manual Title With No Mood Metadata'; noMatchesApp.node('#movies').dispatch('input');
noMatchesApp.node('#draw-mode').value = 'doors'; noMatchesApp.node('#draw-mode').dispatch('change');
noMatchesApp.node('#filter-mood-scary').checked = true; noMatchesApp.node('#filter-mood-scary').dispatch('change');
assert.equal(vm.runInContext('eligibleRecords().length', noMatchesApp.sandbox), 0, 'empty filters keep the shared eligible pool empty');
assert.equal(noMatchesApp.node('#spin').disabled, true, 'empty filters cannot start any draw mode');
assert.equal(noMatchesApp.node('#doors').children.length, 0, 'empty filters do not offer mystery doors');
console.log('Passed: original collection and migrations through v5; PT/EN and theme preferences; watched and filter behavior; surprise sessions and one-to-three-film marathons; shared Halloween draw modes with 1, 2, 3 and 9 eligible films; result/history consistency, manual titles without posters, Wall of Fame, audio, wheel alignment and reduced motion; TMDB proxy and local catalogue; share previews and limits; playlist/backup export, validation, merge, confirmed replacement, restore and corruption handling.');
