import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import { webcrypto } from 'node:crypto';

async function createApp(seed = {}) {
  const nodes = new Map();
  function node(selector) {
    if (!nodes.has(selector)) {
      const classes = new Set();
      nodes.set(selector, { value: '', textContent: '', innerHTML: '', disabled: false, checked: true, hidden: false, children: [], attributes: {}, listeners: {}, classList: { add(...names) { names.forEach(n => classes.add(n)); }, remove(...names) { names.forEach(n => classes.delete(n)); }, toggle(name, force) { if (force ?? !classes.has(name)) classes.add(name); else classes.delete(name); }, contains: name => classes.has(name) }, addEventListener(type, fn) { this.listeners[type] = fn; }, dispatch(type) { return this.listeners[type]?.({ target: this }); }, setAttribute(name, value) { this.attributes[name] = value; }, getAttribute(name) { return this.attributes[name] ?? null; }, replaceChildren() { this.children = []; }, append(...items) { this.children.push(...items); } });
    }
    return nodes.get(selector);
  }
  const canvasContext = { createRadialGradient() { return { addColorStop() {} }; }, clearRect() {}, save() {}, restore() {}, translate() {}, rotate() {}, beginPath() {}, moveTo() {}, arc() {}, closePath() {}, fill() {}, stroke() {}, fillText() {}, measureText: text => ({ width: text.length * 14 }) };
  node('#wheel').getContext = () => canvasContext;
  const storage = new Map(Object.entries(seed).map(([key, value]) => [key, JSON.stringify(value)]));
  const audios = [];
  const animationFrames = [];
  let now = 0;
  let reduceMotion = false;
  let confirmDecision = false;
  const sandbox = vm.createContext({ document: { querySelector: node, createElement: () => ({ textContent: '', append() {}, children: [] }), fonts: null }, localStorage: { getItem: k => storage.get(k) ?? null, setItem: (k, v) => storage.set(k, v) }, Audio: class { constructor(src) { this.src = src; this.paused = true; this.playCount = 0; audios.push(this); } play() { this.paused = false; this.playCount++; return Promise.resolve(); } pause() { this.paused = true; } }, crypto: webcrypto, matchMedia: () => ({ matches: reduceMotion }), performance: { now: () => now }, requestAnimationFrame: fn => animationFrames.push(fn), confirm: () => confirmDecision });
  vm.runInContext(await readFile('movies.js', 'utf8'), sandbox);
  vm.runInContext(await readFile('app.js', 'utf8'), sandbox);
  return { node, storage, audios, animationFrames, sandbox, setNow: value => { now = value; }, setReduceMotion: value => { reduceMotion = value; }, setConfirm: value => { confirmDecision = value; } };
}

const app = await createApp();
const { node, storage, audios, animationFrames, sandbox } = app;
const evaluate = expression => vm.runInContext(expression, sandbox);
assert.equal(node('#count').textContent, 19);
assert.equal(node('#movie-summary-count').textContent, 19);
assert.equal(node('#movie-editor').hidden, true);
assert.equal(node('#edit-toggle').getAttribute('aria-expanded'), 'false');
assert.equal(node('#sound').getAttribute('aria-pressed'), 'true');
assert.equal(node('#sound').getAttribute('aria-label'), 'Desativar som');
assert.equal(audios.every(audio => audio.playCount === 0), true, 'page load must not autoplay');
assert.equal(node('#history-stats').textContent, '17 filmes diferentes · 24 sorteios');
assert.equal(node('#history').children.length, 5);
assert.equal(node('#history-toggle').hidden, false);
node('#history-toggle').dispatch('click');
assert.equal(node('#history').children.length, 17);
assert.equal(node('#history-toggle').textContent, 'Mostrar menos');
node('#history-toggle').dispatch('click');
assert.equal(node('#history').children.length, 5);

node('#edit-toggle').dispatch('click');
assert.equal(node('#movie-editor').hidden, false);
node('#movies').value = 'Only one\nOnly one\n'; node('#movies').dispatch('input');
assert.equal(node('#count').textContent, 1); assert.equal(node('#spin').disabled, true);
assert.match(node('#list-status').textContent, /pelo menos 2/);
assert.equal(evaluate('spin()'), undefined);
node('#movies').value = 'A\nB'; node('#movies').dispatch('input');
assert.equal(evaluate('movieList().length'), 2, 'duplicates are removed');
const originalMovies = node('#movies').value;
node('#reset').dispatch('click');
assert.equal(node('#count').textContent, 19, 'reset restores the original selection');
node('#movies').value = originalMovies; node('#movies').dispatch('input');
node('#finish-edit').dispatch('click');
assert.equal(node('#movie-editor').hidden, true);
assert.equal(node('#list-status').textContent, 'Lista pronta para rodar', 'validity remains visible while collapsed');

node('#sound').dispatch('click');
assert.equal(node('#sound').getAttribute('aria-pressed'), 'false');
assert.equal(node('#sound').getAttribute('aria-label'), 'Ativar som');
assert.equal(JSON.parse(storage.get('halloween-sound-v1')), false);
node('#sound').dispatch('click');
assert.equal(JSON.parse(storage.get('halloween-sound-v1')), true);
const pendingSpin = evaluate('spin()');
assert.equal(animationFrames.length, 1);
assert.equal(audios[0].paused, false, 'roll sound starts during spin when enabled');
assert.equal(node('#movies').disabled, true); assert.equal(node('#reset').disabled, true);
node('#sound').dispatch('click');
assert.equal(audios.every(audio => audio.paused), true, 'disabling sound silences all audio immediately');
assert.equal(JSON.parse(storage.get('halloween-sound-v1')), false);
node('#sound').dispatch('click');
assert.equal(audios[0].paused, false, 'reenabling sound resumes the wheel while spinning');
assert.equal(node('#edit-toggle').disabled, true, 'editor cannot open during a spin');
app.setNow(5000); animationFrames.shift()(5000);
const result = await pendingSpin;
assert.ok(['A', 'B'].includes(result.movie));
assert.equal(node('#result-title').textContent, result.movie);
assert.equal(node('#result').classList.contains('winner'), true);
assert.equal(node('#movies').disabled, false); assert.equal(node('#reset').disabled, false);
assert.equal(audios[0].paused, true);
assert.equal(audios[1].paused, false, 'ending chime plays after the spin when enabled');
const selectedByPointer = evaluate('Math.floor(((Math.PI * 2 - rotation) % (Math.PI * 2)) / (Math.PI * 2 / movieList().length))');
assert.equal(['A', 'B'][selectedByPointer], result.movie);
assert.equal(evaluate('winningIndex'), selectedByPointer, 'highlighted slice matches pointer and announcement');
assert.equal(JSON.parse(storage.get('halloween-history-v1'))[result.movie], 1);

node('#sound').dispatch('click');
assert.equal(audios.every(audio => audio.paused), true, 'turning sound off after the spin silences the chime');
node('#movies').value = Array.from({ length: 61 }, (_, i) => `Film ${i}`).join('\n'); node('#movies').dispatch('input');
assert.equal(node('#spin').disabled, true); assert.match(node('#list-status').textContent, /Máximo de 60/);
node('#movies').value = Array.from({ length: 60 }, (_, i) => `Film ${i}`).join('\n'); node('#movies').dispatch('input');
assert.equal(node('#spin').disabled, false);

const emptyHistory = await createApp({ 'halloween-history-v1': {} });
assert.equal(emptyHistory.node('#history-stats').textContent, '0 filmes diferentes · 0 sorteios');
assert.equal(emptyHistory.node('#history').children.length, 1);
assert.equal(emptyHistory.node('#history-toggle').hidden, true);
const fiveHistory = await createApp({ 'halloween-history-v1': Object.fromEntries(Array.from({ length: 5 }, (_, i) => [`Film ${i}`, 1])) });
assert.equal(fiveHistory.node('#history').children.length, 5);
assert.equal(fiveHistory.node('#history-toggle').hidden, true);
const clearHistory = await createApp({ 'halloween-history-v1': { 'Film A': 2 } });
clearHistory.node('#clear-history').dispatch('click');
assert.equal(clearHistory.node('#history-stats').textContent, '1 filmes diferentes · 2 sorteios', 'declining confirmation preserves history');
clearHistory.setConfirm(true); clearHistory.node('#clear-history').dispatch('click');
assert.equal(clearHistory.node('#history-stats').textContent, '0 filmes diferentes · 0 sorteios', 'history clears only after confirmation');
const reducedMotion = await createApp();
reducedMotion.setReduceMotion(true);
const reducedSpin = vm.runInContext('spin()', reducedMotion.sandbox);
assert.equal(reducedMotion.animationFrames.length, 1);
reducedMotion.animationFrames.shift()(0);
assert.ok((await reducedSpin).movie);
assert.equal(reducedMotion.animationFrames.length, 0, 'reduced motion completes without animation frames');
const longTitles = ['A Very Long Full Movie Title That Must Remain Intact (2026)', 'Another Complete Movie Title (2025)'];
const longTitleApp = await createApp({ 'halloween-movies-v1': longTitles.join('\n') });
const longTitleSpin = vm.runInContext('spin()', longTitleApp.sandbox);
longTitleApp.setNow(5000); longTitleApp.animationFrames.shift()(5000);
const longTitleResult = await longTitleSpin;
assert.ok(longTitles.includes(longTitleResult.movie));
assert.equal(longTitleApp.node('#result-title').textContent, longTitleResult.movie, 'long selected title remains complete in the result');
assert.equal(longTitleApp.node('#movies').value, longTitles.join('\n'), 'editor keeps the complete movie titles');
const persisted = await createApp({ 'halloween-movies-v1': 'Persisted One\nPersisted Two', 'halloween-history-v1': { 'Persisted One': 9 }, 'halloween-sound-v1': false });
assert.equal(persisted.node('#movies').value, 'Persisted One\nPersisted Two');
assert.equal(persisted.node('#history-stats').textContent, '1 filmes diferentes · 9 sorteios');
assert.equal(persisted.node('#sound').getAttribute('aria-pressed'), 'false');
assert.equal(persisted.audios.every(audio => audio.playCount === 0), true);
const html = await readFile('index.html', 'utf8');
const css = await readFile('style.css', 'utf8');
assert.match(html, /Wall of Fame/); assert.match(html, /aria-live="polite"/); assert.match(html, /<svg/);
assert.match(css, /:focus-visible/); assert.match(css, /prefers-reduced-motion:reduce/); assert.match(css, /min-width:44px/);
console.log('Passed: audio toggling before/during/after spin, persistence, history 0/5/>5, list editing/reset/deduplication/bounds, pointer/result/highlight alignment, keyboard focus/accessibility and reduced-motion hooks.');
